version: '4.0.2'

volumes:
  config_data:

services:

  config-store:
    image: thenuzv/config-store:latest
    volumes:
      - config_data:/shared-configs
    restart: "no"

#docker build -t auradocsv4/auradocsv4_abans:config-store-latest .
#docker push auradocsv4/auradocsv4_abans:config-store-latest