spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://auradocslive.mysql.database.azure.com:3306/auradocs_ab_securitasv4?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: abs_v4
    password: kGzEYzKdkl2fzysZu4mR
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    elasticsearch:
      repositories:
        enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    # healthcheck:
    #   enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}-${random.int}
    # hostname: localhost

services:
  archive:
    url: http://archive/metadata

redis:
  host: redis
  port: 6379
cache:
  type: redis

member:
  rent:
    min: 8
    max: 31
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all

openapi:
  service:
    url: http://api-service:8080

app:
  cors:
    allowed-origins: http://absecuritas.southindia.cloudapp.azure.com, http://absecuritas.eastus.cloudapp.azure.com

management:
  health:
    elasticsearch:
      enabled: false
    reactive-elasticsearch:
      enabled: false