spring:
  application:
    name: image
  profiles:
    active: dev
  banner:
    location: classpath:banner.txt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auradocs_auradot?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Aura2528@
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: vthenujan7400@gmail.com
    password: vicslqxelpvxbbxg
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    # healthcheck:
    #   enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}-${random.int}
    # hostname: localhost

member:
  rent:
    min: 8
    max: 31
  price:
    discount: 3
vehicle:
  default:
    model: cross over
duration: all

site: 
  file-share:
    url: http://localhost:9191/share-doc/view/


server:
  port: 0

archive:
  location: /var/tmp/auradocsv4
  identity: archive_1
  pending-docs:
    location: /var/tmp/auradocsv4/archive/documents
  signature-img: signature
  thumbs-location: /var/tmp/auradocsv4/thumbs
temp:
  location: /var/tmp/auradocsv4/temp
  auto-sign: sign
combinedDocs:
  location: /var/tmp/auradocsv4/temp
bookmark: 
  location: /var/tmp/bookmark

management: 
  tracing: 
    sampling: 
      probability: 1.0 
      
hystrix:
  timeout: 5000
  
services:
  user: 
    url: http://user/micro
    group-url: http://user/auth/group
    user-key: http://user/user-key
  search:
    active: ES   # possible values [DB, ES]
    cron-url: http://search/cronjobs
  fileaccess-track:
    url: http://fileaccess-track/logging
  archive:
    url: http://archive/metadata
  template: 
    url: http://template/template
    micro: http://template/template-micro
  email-notification:
    url: http://notification/email-manager
  sms-notification:
    url: http://notification/sms-manager

openapi:
  service:
    title: Image Service
    description: Image Processing related micro service for the AuraDOCS V4 
    version: 1.0.0-SNAPSHOT
    url: http://localhost:9191
  contact:
    name: AuraDOT PVT Ltd.
    email: contact@auradot.com
springdoc: 
  api-docs:
    path: /image/api-docs
  swagger-ui: 
    path: /image/swagger-ui.html

undersecretary:
  key:
    password: "auradocsuserkeystore"